# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call(`_fastcats_rcppeigen_hello_world`)
}

rcppeigen_outerproduct <- function(x) {
    .Call(`_fastcats_rcppeigen_outerproduct`, x)
}

rcppeigen_innerproduct <- function(x) {
    .Call(`_fastcats_rcppeigen_innerproduct`, x)
}

rcppeigen_bothproducts <- function(x) {
    .Call(`_fastcats_rcppeigen_bothproducts`, x)
}

